//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PRINCE_STGEntities : DbContext
    {
        public PRINCE_STGEntities()
            : base("name=PRINCE_STGEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<STG_DIM_STORE> STG_DIM_STORE { get; set; }
        public virtual DbSet<SuperiorMaintenance> SuperiorMaintenance { get; set; }
        public virtual DbSet<TEMP_DC> TEMP_DC { get; set; }
        public virtual DbSet<TEMP_STORE> TEMP_STORE { get; set; }
        public virtual DbSet<TEMP_STOREDC> TEMP_STOREDC { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserMenu> UserMenu { get; set; }
        public virtual DbSet<Site> Site { get; set; }
        public virtual DbSet<STG_STR_MERCH_DET> STG_STR_MERCH_DET { get; set; }
        public virtual DbSet<STG_STR_FOOTFALL> STG_STR_FOOTFALL { get; set; }
        public virtual DbSet<STG_TARGET> STG_TARGET { get; set; }
        public virtual DbSet<STG_FORECAST> STG_FORECAST { get; set; }
        public virtual DbSet<STG_PLAN> STG_PLAN { get; set; }
        public virtual DbSet<STG_DIM_PRICE_BAND> STG_DIM_PRICE_BAND { get; set; }
        public virtual DbSet<STG_DIM_STOCKAGE_BAND> STG_DIM_STOCKAGE_BAND { get; set; }
    }
}
