//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_STR_MERCH_DET
    {
        public int ID { get; set; }
        public System.DateTime STRMRGRP_DATE { get; set; }
        public string STORE_CODE { get; set; }
        public string PROD_LEVEL1_CODE { get; set; }
        public string PROD_LEVEL2_CODE { get; set; }
        public string PROD_LEVEL3_CODE { get; set; }
        public string PROD_LEVEL4_CODE { get; set; }
        public decimal SELLING_AREA { get; set; }
        public decimal TOTAL_AREA { get; set; }
        public int PERMENANT_FTE { get; set; }
        public int CONTRACT_FTE { get; set; }
        public Nullable<decimal> OTH_DET1 { get; set; }
        public Nullable<decimal> OTH_DET2 { get; set; }
        public Nullable<decimal> OTH_DET3 { get; set; }
        public Nullable<decimal> OTH_DET4 { get; set; }
        public Nullable<decimal> OTH_DET5 { get; set; }
        public Nullable<System.DateTime> ARC_DATE { get; set; }
    }
}
