//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_DIM_STORE
    {
        public string STORE_CODE { get; set; }
        public string STORE_DESCRIPTION { get; set; }
        public string STORE_SHORT_DESCRIPTION { get; set; }
        public string GEO_LEVEL1_CODE { get; set; }
        public string GEO_LEVEL1_DESC { get; set; }
        public string GEO_LEVEL2_CODE { get; set; }
        public string GEO_LEVEL2_DESC { get; set; }
        public string GEO_LEVEL3_CODE { get; set; }
        public string GEO_LEVEL3_DESC { get; set; }
        public string GEO_LEVEL4_CODE { get; set; }
        public string GEO_LEVEL4_DESC { get; set; }
        public string GEO_LEVEL5_CODE { get; set; }
        public string GEO_LEVEL5_DESC { get; set; }
        public string STORE_ADDRESS1 { get; set; }
        public string STORE_ADDRESS2 { get; set; }
        public string STORE_PHONE_NO { get; set; }
        public string STORE_FAX_NO { get; set; }
        public string STORE_ZIP { get; set; }
        public string STORE_TYPE { get; set; }
        public string STORE_GROUP { get; set; }
        public string STORE_STATUS { get; set; }
        public string STORE_FORMAT { get; set; }
        public string FRANCHISEE_FLG { get; set; }
        public string FRANCHISEE_OWNER { get; set; }
        public Nullable<System.DateTime> STORE_OPENING_DATE { get; set; }
        public Nullable<System.DateTime> STORE_OPENING_HOURS { get; set; }
        public Nullable<System.DateTime> STORE_CLOSING_HOURS { get; set; }
        public Nullable<System.DateTime> STORE_CLOSING_DATE { get; set; }
        public string GROUP_CURRENCY_CODE { get; set; }
        public string CURRENCY_CODE { get; set; }
        public string DC_STORE_CODE { get; set; }
        public string DC_STORE_DESCRIPTION { get; set; }
        public string WH_STORE_CODE { get; set; }
        public string WH_STORE_DESCRIPTION { get; set; }
        public string BANNER { get; set; }
        public string STORE_LATITUDE { get; set; }
        public string STORE_LONGITUDE { get; set; }
        public string STORE_ATTRIBUTE1 { get; set; }
        public string STORE_ATTRIBUTE2 { get; set; }
        public string STORE_ATTRIBUTE3 { get; set; }
        public string STORE_ATTRIBUTE4 { get; set; }
        public string STORE_ATTRIBUTE5 { get; set; }
        public Nullable<System.DateTime> ARC_DATE { get; set; }
        public string CHANNEL_CODE { get; set; }
        public string CHANNEL_DESCRIPTION { get; set; }
        public string CHANNEL_GROUP_CODE { get; set; }
        public string CHANNEL_GROUP_DESC { get; set; }
    }
}
