//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_DIM_PRICE_BAND
    {
        public int ID { get; set; }
        public string PRICE_BAND_CODE { get; set; }
        public string PRICE_BAND_DESC { get; set; }
        public string PROD_LEVEL1_CODE { get; set; }
        public Nullable<decimal> PRICE_BAND_LOWER { get; set; }
        public Nullable<decimal> PRICE_BAND_UPPER { get; set; }
        public Nullable<int> PRICE_BAND_SEQ { get; set; }
        public System.DateTime ARC_DATE { get; set; }
    }
}
