//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_STR_FOOTFALL
    {
        public System.DateTime FOOTFALL_DATE { get; set; }
        public string STORE_CODE { get; set; }
        public Nullable<int> FOOTFALL_COUNT { get; set; }
        public Nullable<System.DateTime> ARC_DATE { get; set; }
    }
}
