//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class STG_DIM_STOCKAGE_BAND
    {
        public int ID { get; set; }
        public string STOCKAGE_BAND_DESC { get; set; }
        public string STKAGE_PROD_LEVEL1_CODE { get; set; }
        public decimal STOCKAGE_BAND_LOWER { get; set; }
        public decimal STOCKAGE_BAND_UPPER { get; set; }
        public int STOCKAGE_BAND_SEQ { get; set; }
        public Nullable<short> LATEST { get; set; }
        public Nullable<System.DateTime> ARC_DATE { get; set; }
    }
}
