//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_STORE
    {
        public int ID { get; set; }
        public string STORE_DESCRIPTION { get; set; }
        public string STORE_CODE { get; set; }
        public string STORE_LATITUDE { get; set; }
        public string STORE_LONGITUDE { get; set; }
        public Nullable<System.DateTime> STORE_OPENING_HOUR { get; set; }
        public Nullable<System.DateTime> STORE_CLOSING_HOUR { get; set; }
        public string SOM { get; set; }
        public string SOM_DESC { get; set; }
        public string SENIOR_SOM { get; set; }
        public string SENIOR_SOM_DESC { get; set; }
        public string AREA_MANAGER { get; set; }
        public string AREA_MANAGER_DESC { get; set; }
        public string REGIONAL_MANAGER { get; set; }
        public string REGIONAL_MANAGER_DESC { get; set; }
    }
}
