//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_DC
    {
        public string DC_STORE_CODE { get; set; }
        public string DC_STORE_DESCRIPTION { get; set; }
    }
}
